print("Welcome to Nick's Mad Lib")
input("Type ready and hit enter when you're ready: ")
print("Good, let's start")
Noun_1 = input("Give me a noun: ")
Noun_2=input("Give me another noun: ")
Verb_1=input("Can you give me a past tense verb please?: ")
Noun_3=input("Noun please: ")
Noun_4=input("Give me a noun: ")
Verb_2=input("One more past-tense verb: ")
input("Last noun and we're done: ")
print("The itsy bitsy spider crawled up the " + Noun_1 )
print("down came the "  +  Noun_2 )
print(" And "  +   Verb_1   +  " the spider out ")
print(" Out came the " + Noun_3)
print(" and dried up all the " + Noun_4)
print(" and the itsy bitsy spider " + Verb_2) 
print("up the spout again")
print("The End")
